Repository wecode-bootcamp-korea/38-1st-weKEA-backend, pull requests merged in 2022-10, with the labels that each got.

#2 [ADD] 초기 세팅 완료
  .env.sample
  .gitignore
  api/controllers/index.js
  api/models/dataSource.js
  api/models/index.js
  api/routes/index.js
  api/services/index.js
  api/utils/auth.js
  api/utils/error.js
  package-lock.json
  package.json
  weKEA.js
Labels: 완료

#3 [ADD] ERD 작성 완료 및 dbmate 활용한 migration 파일 완성
  .DS_Store
  .env.sample
  .gitignore
  api/models/dataSource.js
  db/.DS_Store
  db/migrations/20221018085449_create_users.sql
  db/migrations/20221018085504_create_categories.sql
  db/migrations/20221018085614_create_products.sql
  db/migrations/20221018085627_create_product_options.sql
  db/migrations/20221018085639_create_carts.sql
  db/migrations/20221018085650_create_images.sql
  db/migrations/20221018085702_create_wishlists.sql
  db/migrations/20221018085709_create_order_status.sql
  db/migrations/20221018085710_create_orders.sql
Labels: 멘토 리뷰 요청

#6 [ADD] sign-up-sign-in
  .env.sample
  api/controllers/index.js
  api/controllers/userController.js
  api/models/dataSource.js
  api/models/index.js
  api/models/userDao.js
  api/routes/index.js
  api/routes/userRouter.js
  api/services/index.js
  api/services/userService.js
  api/utils/auth.js
  api/utils/error.js
  db/migrations/20221018085449_create_users.sql
  db/migrations/20221018085709_create_order_status.sql
  package-lock.json
  weKEA.js
Labels: 완료

#7 [ADD] 제품상세페이지 API 구현
  api/controllers/index.js
  api/controllers/productController.js
  api/models/dataSource.js
  api/models/index.js
  api/models/productDao.js
  api/models/userDao.js
  api/routes/index.js
  api/routes/productRouter.js
  api/services/index.js
  api/services/productService.js
  api/services/userService.js
  db/migrations/20221018085449_create_users.sql
  package-lock.json
Labels: 멘토 리뷰 요청

#12 migration 파일 추가
  db/migrations/20221018085639_create_carts.sql
  db/migrations/20221024082735_update_carts.sql
  db/migrations/20221024082745_update_orders.sql
Labels: 멘토 리뷰 요청

#13 [ADD] 마이페이지 유저정보 불러오기
  api/controllers/userController.js
  api/models/userDao.js
  api/routes/userRouter.js
  api/services/userService.js
  api/utils/auth.js
Labels: 멘토 리뷰 요청

#11 [ADD] 카테고리별 상품 정렬 및 가격범위 필터링
  api/controllers/categoryController.js
  api/controllers/index.js
  api/controllers/userController.js
  api/models/categoryDao.js
  api/models/index.js
  api/models/userDao.js
  api/routes/categoryRouter.js
  api/routes/index.js
  api/services/categoryService.js
  api/services/index.js
  api/services/userService.js
  package-lock.json
Labels: 멘토 리뷰 요청

#10 [ADD] 구매내역 페이지 API 구현
  api/controllers/index.js
  api/controllers/orderController.js
  api/models/enums.js
  api/models/index.js
  api/models/orderDao.js
  api/models/userDao.js
  api/routes/index.js
  api/routes/orderRouter.js
  api/services/index.js
  api/services/orderService.js
Labels: 멘토 리뷰 요청, 완료

#14 [MODIFY] 예외 핸들링 위한 service단 PRICERANGE 함수 수정
  api/services/categoryService.js
Labels: 멘토 리뷰 요청

#15 [Modify] productDao sub query문으로 바꿈
  .DS_Store
  api/.DS_Store
  api/models/productDao.js
Labels: 멘토 리뷰 요청

#8 [ADD] 장바구니 페이지 완성
  api/controllers/cartController.js
  api/controllers/index.js
  api/controllers/userController.js
  api/models/cartDao.js
  api/models/index.js
  api/models/wishlistDao.js
  api/routes/cartRouter.js
  api/routes/index.js
  api/services/cartService.js
  api/services/index.js
Labels: 멘토 리뷰 요청

#5 [ADD] main-page API 구현
  api/controllers/productController.js
  api/models/productDao.js
  api/routes/index.js
  api/routes/productRouter.js
  api/services/productService.js
  api/services/userService.js
  db/.DS_Store
Labels: 멘토 리뷰 요청

#9 [ADD] wishlist 기능 구현
  api/controllers/index.js
  api/controllers/wishlistController.js
  api/models/index.js
  api/models/wishlistDao.js
  api/routes/index.js
  api/routes/wishlistRouter.js
  api/services/index.js
  api/services/wishlistService.js
Labels: 멘토 리뷰 요청
